name: ğŸ“ˆ Performance check
on: [push]
jobs:
    lighthouseci:
        runs-on: ubuntu-latest
        steps:
            - name: ğŸ‘ Checkout
              uses: actions/checkout@v3

            - name: ğŸ‘ Use Node.js 16.x
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x

            - name: ğŸ“¥ Install Dependecies
              run: npm install && npm install -g @lhci/cli@0.13.x

            - name: ğŸ—ï¸ Build App
              run: npm run build

            - name: ğŸš¨ Run Lighthouse
              run: lhci autorun
